/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Bean.VerboBean;
import Dao.ListaVerboDao;
import Dao.VerboEliminadoDao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class VistaListaVerbo extends javax.swing.JFrame {

    DefaultTableModel tabla;
    private int idVerbo;

    /**
     * Creates new form VistaListaVerbo
     */
    public VistaListaVerbo() {
        initComponents();
        setResizable(false);//no se maximice la pantalla
        setLocationRelativeTo(null);//aparezca enmedio
        this.consultarVerbos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVerbos = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        btnVerbosEliminados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Lista de verbos");

        tablaVerbos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaVerbos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVerbosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaVerbos);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnVerbosEliminados.setText("Papeleria de reciclaje");
        btnVerbosEliminados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerbosEliminadosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVerbosEliminados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegresar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(btnVerbosEliminados))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VistaPrincipal vistaPrincipal = new VistaPrincipal();
        vistaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnVerbosEliminadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerbosEliminadosMouseClicked

        VistaVerbosEliminados vistaVerbosEliminados = new VistaVerbosEliminados();
        vistaVerbosEliminados.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVerbosEliminadosMouseClicked

    private void tablaVerbosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVerbosMouseClicked
        evt.getPoint();
        int seleccionado = this.tablaVerbos.rowAtPoint(evt.getPoint());
        this.idVerbo = Integer.parseInt(this.tablaVerbos.getValueAt(seleccionado, 0).toString());

        String[] opciones = {"Eliminar verbo", "Modificar verbo"};
        String respuesta = (String) JOptionPane.showInputDialog(null, "Seleccione una opción",
                "Seleccione una opción", JOptionPane.DEFAULT_OPTION, null, opciones, opciones[0]);

        int dialogButton;

        if (respuesta.equals("Eliminar verbo")) {

            dialogButton = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el verbo?", "Eliminar verbo",
                    JOptionPane.YES_NO_OPTION);

            if (dialogButton == JOptionPane.YES_OPTION) {

                int[] ids = ListaVerboDao.consultarIds(this.idVerbo);
                boolean eliminado = ListaVerboDao.eliminarVerbo(ids);
                if (eliminado) {
                    this.consultarVerbos();
                    JOptionPane.showMessageDialog(this, "Verbo movido a papelera de reciclaje");
                } else {
                    JOptionPane.showMessageDialog(this, "Ocurrio un error al eliminar");
                }
            } else if (dialogButton == JOptionPane.NO_OPTION) {

            }

        } else if (respuesta.equals("Modificar verbo")) {

            dialogButton = JOptionPane.showConfirmDialog(null, "¿Desea modificar el verbo?", "Modificar verbo",
                    JOptionPane.YES_NO_OPTION);

            if (dialogButton == JOptionPane.YES_OPTION) {

            } else if (dialogButton == JOptionPane.NO_OPTION) {

            }

        }
    }//GEN-LAST:event_tablaVerbosMouseClicked

    public void consultarVerbos() {
        tabla = new DefaultTableModel(new String[]{"Nº", "Español", "Infinitivo", "Pasado simple",
            "Pasado participio",}, 0);

        List<VerboBean> listaVerbos = ListaVerboDao.consultarVerbos();

        for (VerboBean verbo : listaVerbos) {
            Object[] objeto = {verbo.getIdEspanol(), verbo.getNombreEspanol(), verbo.getNombreInfinitivo(),
                verbo.getNombrePasadoSimple(), verbo.getNombrePasadoParticipio()};
            tabla.addRow(objeto);
        }

        tablaVerbos.setModel(tabla);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaListaVerbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaListaVerbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaListaVerbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaListaVerbo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaListaVerbo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVerbosEliminados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaVerbos;
    // End of variables declaration//GEN-END:variables
}
