/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Bean.VerboBean;
import Dao.ModificarVerboDao;
import Dao.PracticarDao;
import java.awt.Color;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class VistaPracticar extends javax.swing.JFrame {

    /**
     * Creates new form VistaPracticar
     */
    int[] idsVerbos;
    VerboBean verbo;
    int id;
    URL url;
    ImageIcon icon;

    public VistaPracticar() {
        initComponents();
        setResizable(false);//no se maximice
        setLocationRelativeTo(null);//aparezca enmedio
        this.cambiarVerbo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        laberEspanol = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnCambiarVerbo = new javax.swing.JButton();
        btnVerRespuesta = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtInfinitivo = new javax.swing.JTextField();
        txtPasadoSimple = new javax.swing.JTextField();
        txtPasadoParticipio = new javax.swing.JTextField();
        btnRevisar = new javax.swing.JButton();
        labelImagenInfinitivo = new javax.swing.JLabel();
        labelImagenPS = new javax.swing.JLabel();
        labelImagenPP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Practicar");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Verbo:");

        laberEspanol.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        laberEspanol.setText("-");

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCambiarVerbo.setText("Cambiar verbo");
        btnCambiarVerbo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCambiarVerboMouseClicked(evt);
            }
        });

        btnVerRespuesta.setText("Ver respuestas");
        btnVerRespuesta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerRespuestaMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Infinitiivo:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Pasado simple:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Pasado participio:");

        btnRevisar.setText("Revisar");
        btnRevisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRevisarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRevisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVerRespuesta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCambiarVerbo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(34, 34, 34)
                                        .addComponent(laberEspanol)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtPasadoSimple, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                                .addComponent(txtPasadoParticipio))
                                            .addComponent(txtInfinitivo, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelImagenInfinitivo, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addComponent(labelImagenPP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(labelImagenPS, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(laberEspanol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelImagenInfinitivo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtInfinitivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPasadoSimple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelImagenPS, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPasadoParticipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelImagenPP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnCambiarVerbo)
                    .addComponent(btnVerRespuesta)
                    .addComponent(btnRevisar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VistaPrincipal vistaPrincipal = new VistaPrincipal();
        vistaPrincipal.setVisible(true);
        this.dispose();
        getContentPane().setBackground(Color.white);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCambiarVerboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiarVerboMouseClicked

        btnRevisar.setEnabled(true);
        btnVerRespuesta.setEnabled(true);

        txtInfinitivo.setText("");
        txtPasadoSimple.setText("");
        txtPasadoParticipio.setText("");

        url = this.getClass().getResource("");
        icon = new ImageIcon(url);
        
        labelImagenInfinitivo.setIcon(icon);
        labelImagenPS.setIcon(icon);
        labelImagenPP.setIcon(icon);

        this.cambiarVerbo();

    }//GEN-LAST:event_btnCambiarVerboMouseClicked

    private void btnVerRespuestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerRespuestaMouseClicked

        txtInfinitivo.setText(verbo.getNombreInfinitivo());
        txtPasadoSimple.setText(verbo.getNombrePasadoSimple());
        txtPasadoParticipio.setText(verbo.getNombrePasadoParticipio());

        btnRevisar.setEnabled(false);
        btnVerRespuesta.setEnabled(false);
    }//GEN-LAST:event_btnVerRespuestaMouseClicked

    private void btnRevisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevisarMouseClicked

        if (!txtInfinitivo.getText().toString().equals("")
                && !txtPasadoParticipio.getText().toString().equals("")
                && !txtPasadoSimple.getText().toString().equals("")) {

            if (txtInfinitivo.getText().toString().toLowerCase().equals(verbo.getNombreInfinitivo().toLowerCase())) {
                url = this.getClass().getResource("/Imagenes/Boton_correcto.png");
                icon = new ImageIcon(url);
                labelImagenInfinitivo.setIcon(icon);
            } else {
                url = this.getClass().getResource("/Imagenes/Boton_error.png");
                icon = new ImageIcon(url);
                labelImagenInfinitivo.setIcon(icon);
            }

            if (txtPasadoSimple.getText().toString().toLowerCase().equals(verbo.getNombrePasadoSimple().toLowerCase())) {
                url = this.getClass().getResource("/Imagenes/Boton_correcto.png");
                icon = new ImageIcon(url);
                labelImagenPS.setIcon(icon);
            } else {
                url = this.getClass().getResource("/Imagenes/Boton_error.png");
                icon = new ImageIcon(url);
                labelImagenPS.setIcon(icon);
            }

            if (txtPasadoParticipio.getText().toString().toLowerCase().equals(verbo.getNombrePasadoParticipio().toLowerCase())) {
                url = this.getClass().getResource("/Imagenes/Boton_correcto.png");
                icon = new ImageIcon(url);
                labelImagenPP.setIcon(icon);
            } else {
                url = this.getClass().getResource("/Imagenes/Boton_error.png");
                icon = new ImageIcon(url);
                labelImagenPP.setIcon(icon);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Favor de llenar todos los campos");
        }

    }//GEN-LAST:event_btnRevisarMouseClicked

    public void cambiarVerbo() {

        int numero;
        List<VerboBean> listaVerbo = new ArrayList<>();
        idsVerbos = PracticarDao.consultarVerbos();

        if (idsVerbos.length > 0) {
            numero = (int) (Math.random() * ((idsVerbos.length - 1) - 0 + 1) + 0);
            id = idsVerbos[numero];

            listaVerbo = PracticarDao.consultarVerbo(id);
            if (!listaVerbo.isEmpty()) {
                verbo = listaVerbo.get(0);
                laberEspanol.setText(verbo.getNombreEspanol());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPracticar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPracticar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPracticar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPracticar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPracticar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarVerbo;
    private javax.swing.JButton btnRevisar;
    private javax.swing.JButton btnVerRespuesta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelImagenInfinitivo;
    private javax.swing.JLabel labelImagenPP;
    private javax.swing.JLabel labelImagenPS;
    private javax.swing.JLabel laberEspanol;
    private javax.swing.JTextField txtInfinitivo;
    private javax.swing.JTextField txtPasadoParticipio;
    private javax.swing.JTextField txtPasadoSimple;
    // End of variables declaration//GEN-END:variables
}
